### ISSUE TITLE
RC to actual release

### ISSUE THREAD

**Issue by jeroenvdgulik** [chrisguitarguy/RequestIdBundle#12]
Could we tag 4.0 ? `composer validate --strict` doesn't seem to like the RC tag, and I think it's stable (enough ?) for an actual release.

**Comment by chrisguitarguy** [comment]
Sorry, kinda forgot about tagging a v4.0 release! I've beenr unning the RC in production for a while now, so I'm good with tagging it

https://github.com/chrisguitarguy/RequestIdBundle/releases/tag/v4.0.0
