### ISSUE TITLE
isMasterRequest is deprecated in symfony 5.3

### ISSUE THREAD

**Issue by SabatierBoris** [chrisguitarguy/RequestIdBundle#20]
After updating Symfony to 5.3, I've got a log of deprecated warning : `Symfony\Component\HttpKernel\Event\KernelEvent::isMasterRequest()" is deprecated, use "isMainRequest()`

After analyzing the call stack, it's from the request-id bundle.
It's seem only come from the `src/EventListener/RequestIdListener.php` file : https://github.com/chrisguitarguy/RequestIdBundle/search?q=isMasterRequest

**Comment by chrisguitarguy** [comment]
`v4.2.1` should have this fixed ‼️
