### ISSUE TITLE
Monolog 3 is not supported

### ISSUE THREAD

**Issue by morawskim** [chrisguitarguy/RequestIdBundle#26]
Hello

To reproduce bug try following commands:

Create a new project `composer create-project symfony/skeleton request-id-bundle-example`
Install monolog `composer require monolog`
Install bundle `composer require chrisguitarguy/request-id-bundle`
Configure this bundle (enable integration with Monolog).

On PHP 8.1 you should get an error, when you try to access `/`

```
Chrisguitarguy\RequestId\Monolog\RequestIdProcessor::__invoke(): Argument #1 ($record) must be of type array, Monolog\LogRecord given, called in /home/marcin/projekty/requestidbundle-test/vendor/monolog/monolog/src/Monolog/Logger.php on line 331
```

Monolog 3 requires PHP 8.1, but also has introduced some changes in API - [UPGRADE instructions for Monolog 3](https://github.com/Seldaek/monolog/blob/main/UPGRADE.md#300)

> Log records have been converted from an array to a Monolog\LogRecord object with public (and mostly readonly) properties. e.g. instead of doing $record['context'] use $record->context. In formatters or handlers if you rather need an array to work with you can use $record->toArray() to get back a Monolog 1/2 style record array. This will contain the enum values instead of enum cases in the level and level_name keys to be more backwards compatible and use simpler data types.

We need to change types for `Chrisguitarguy\RequestId\Monolog\RequestIdProcessor::__invoke` to support Monolog 3 and previous versions. Because this bundle support PHP 7.4 we cannot use Union types.
My idea is to remove types and check variable's type `$record` in method.

I will prepare PR soon (to end of this week).

**Comment by chrisguitarguy** [comment]
In https://github.com/chrisguitarguy/RequestIdBundle/pull/27 !!
